### ISSUE TITLE
编译可执行文件

### ISSUE THREAD

**Issue by zheshinicheng** [tun2proxy/socks5-impl#1]
您好，我不知道如何编译`dns2socks`
在overtls编译时我使用`cross build --release --target x86_64-unknown-linux-musl`就能成功得到便编译后的可执行文件。
在`dns2socks`中应该如何编译才能得到可执行文件。
好吧，我这个问题好愚蠢。期待您的回复。

**Comment by ssrlive** [comment]
https://github.com/ssrlive/socks5-impl/blob/3ae512dc5be080e336b49294c72c14a066365642/.github/workflows/release.yml#L54-L58

**Comment by zheshinicheng** [comment]
好的，谢谢您
